### PR TITLE
Use `/dev/uesrfaultfd`, when it exists, to create the file descriptor

### PR DESCRIPTION
**Pull request by bchalios**
Since kernel 6.1, Linux introduced a new interface to create userfault file descriptors, via a new `USERFAULTFD_IOC_NEW` `ioctl()` issued to the `/dev/userfaultd` newly added device. Creating the file descriptor using this interface does not require the process to have the `CAP_SYS_PTRACE` capability, which is the case now if it does not define the `UFFD_USER_MODE_ONLY` flag. Access to `/dev/userfaultfd` is governed by normal file system permissions. Flags passed to the `USERFAULTFD_IOC_NEW` `ioctl()` are the same as the ones passed to the system call.

This PR changes the way we create the file descriptor. If `/dev/userfaultfd` is present, we will try to create the file descriptor issuing the `ioctl()` to it. Otherwise, it will fall back to calling the system call.

### CODE REVIEW

**Comment by pchickey** [comment]
This implementation looks great, but I'm not familiar with this new kernel interface. I'll leave this PR open for a little bit so that hopefully someone who knows that interface better can take a look.

**Comment by bchalios** [comment]
Thanks for the response @pchickey!

Just as additional context, kernel documentation about the API can be found [here]( https://www.kernel.org/doc/html/v6.1/admin-guide/mm/userfaultfd.html). Also, crosvm implements the same logic but [within their project](https://github.com/google/crosvm/blob/8582fde1ceb63b747e965c14ae74904e3d11a36d/swap/src/userfaultfd.rs#L190).

For what is worth, I consumed the API in a [PR I opened for Firecracker](https://github.com/firecracker-microvm/firecracker/pull/4086) and everything seems to be working.

**Comment by bchalios** [comment]
Hey @pchickey. Did you maybe have time to take a look into this? Please, let me know if there's anything I can do to help with the review.

Without this, we are observing issues in Firecracker with kernels 6.1, so it would be nice to have a solution upstream.

**Review by pchickey — APPROVED** [review]

**Comment by pchickey** [comment]
@bchalios I sent you an invite to commit to this repo, and publish the crates. Once you accept you can please approve #57, hit merge, checkout the merged main locally, and publish the crates.

**Comment by bchalios** [comment]
Wow! Thanks I guess :) I see the CI is failing on `main`. I assume it is because we don't have access to the `/dev/userfaultfd` device. I'll fix this before making the release. Does that make sense to you?

**Comment by pchickey** [comment]
Oh, I didn't see that until now. Yes, lets get the fix in for handling access denied before the release.

**Pull request merged**
